# Generated by Django 5.0 on 2024-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logger_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='time_log',
        ),
    ]
