# Generated by Django 5.0 on 2024-05-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_logger_time_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
