# Generated by Django 5.0 on 2024-07-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reservation_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
