# Generated by Django 5.0 on 2024-08-01 12:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Main_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
